# data set
'dataset_path': '../cc_project/BreaKHis_v1/'
'output_dir' : './output/'
'log_dir' : ''
'classes': ['fibroadenoma', 'phyllodes_tumor', 'tubular_adenoma', 'adenosis','mucinous_carcinoma',
            'ductal_carcinoma', 'lobular_carcinoma', 'papillary_carcinoma']
'magnification': '40X'
'magnifications' : ['40X', '100X', '200X', '400X']
'tumor_types' : ['benign', 'malignant']
'benign' : ['fibroadenoma', 'phyllodes_tumor', 'tubular_adenoma', 'adenosis']
'malignant' : ['mucinous_carcinoma', 'ductal_carcinoma', 'lobular_carcinoma', 'papillary_carcinoma']
'flip': [0,1,-1]
# train
'fine_tuning': False
'layer_name': 'Conv2'
'feature_extractor': 'ResNet50'
'mlp': 1
'model_name': 'breakHis_mlp'
'dataset_for_datagen' : './breakHis_datagen/'
'train_batch_size': 1
'test_batch_size': 1
'predict_batch_size': 20
'epochs' : 1
'class_mode': 'categorical'
'early_stopping_monitor': 'val_accuracy'
'early_stopping_mode': 'max'
'early_stopping_patience' : 5
'input_width' : 32
'input_depth' : 32
'valid_split' : 0.1
'test_split' : 0.2
'metrics': 'accuracy'
'optimizer': 'Adam'
'loss': 'categorical_crossentropy'
